version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "odsn-qjdl-7284-9452"
      MYSQL_DATABASE: "aldeamo"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "lpsj-dfxs-7234-9473"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local
